name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build application
        run: |
          # Go Tidy
          go mod tidy
          # Frontend build
          cd frontend
          npm install
          npm run build
          cd ..
          # Copy frontend assets to backend
          cp -R ./frontend/dist ./backend/dist
          # Backend build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o infoclash-linux-amd64 ./backend
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o infoclash-windows-amd64.exe ./backend
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o infoclash-macos-arm64 ./backend
          # Clean up
          rm -rf ./backend/dist

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            infoclash-linux-amd64
            infoclash-windows-amd64.exe
            infoclash-macos-arm64